package kotlinx.coroutines.internal;

/* compiled from: CoroutineExceptionHandlerImpl.common.kt */
/* loaded from: classes4.dex */
public final class ExceptionSuccessfullyProcessed extends Exception {

    /* renamed from: f  reason: collision with root package name */
    public static final ExceptionSuccessfullyProcessed f19467f = new ExceptionSuccessfullyProcessed();

    private ExceptionSuccessfullyProcessed() {
    }
}
